# Generated by Django 2.2.8 on 2020-01-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Synagogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('in_israel', models.BooleanField(default=True)),
                ('in_jerusalem', models.BooleanField(default=False)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('member_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True)),
                ('maiden_name', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_birth_after_sunset', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('date_of_death_after_sunset', models.BooleanField(default=False)),
                ('gender', django_enumfield.db.fields.EnumField(blank=True, default=None, enum=webapp.models.Gender, null=True)),
                ('is_member', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.TextField(blank=True)),
                ('yichus', django_enumfield.db.fields.EnumField(blank=True, default=None, enum=webapp.models.Yichus, null=True)),
                ('manual_paternal_name', models.TextField(blank=True)),
                ('manual_maternal_name', models.TextField(blank=True)),
                ('cannot_get_aliya', models.BooleanField(default=False)),
                ('can_be_hazan', models.BooleanField(default=False)),
                ('can_read_torah', models.BooleanField(default=False)),
                ('can_read_haftarah', models.BooleanField(default=False)),
                ('bar_mitzvah_parasha', models.IntegerField(blank=True, choices=[(0, 'Beraishis'), (1, 'Noach'), (2, "Lech L'cha"), (3, 'Vayera'), (4, 'Chayei Sarah'), (5, 'Toldos'), (6, 'Vayetzei'), (7, 'Vayishlach'), (8, 'Vayeshev'), (9, 'Miketz'), (10, 'Vayigash'), (11, 'Vayechi'), (12, 'Shemos'), (13, "Va'era"), (14, 'Bo'), (15, 'Beshalach'), (16, 'Yisro'), (17, 'Mishpatim'), (18, 'Teruma'), (19, 'Tetzave'), (20, 'Ki Sisa'), (21, 'Vayakhel'), (22, 'Pekudei'), (23, 'Vayikra'), (24, 'Tzav'), (25, 'Shemini'), (26, 'Tazria'), (27, 'Metzora'), (28, 'Acharei Mos'), (29, 'Kedoshim'), (30, 'Emor'), (31, 'Behar'), (32, 'Bechukosai'), (33, 'Bamidbar'), (34, 'Naso'), (35, "Beha'aloscha"), (36, 'Shelach'), (37, 'Korach'), (38, 'Chukas'), (39, 'Balak'), (40, 'Pinchas'), (41, 'Matos'), (42, "Ma'sei"), (43, 'Devarim'), (44, "Va'eschanan"), (45, 'Eikev'), (46, "R'ey"), (47, 'Shoftim'), (48, 'Ki Setzei'), (49, 'Ki Savo'), (50, 'Netzavim'), (51, 'Vayelech'), (52, 'Haazinu'), (53, "V'zos Habrocha")], null=True)),
                ('last_aliya_date', models.DateField(blank=True, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_father', to='webapp.Person')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='webapp.Person')),
                ('synagogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Synagogue')),
                ('wife', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='husband', to='webapp.Person')),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
    ]
