# Generated by Django 2.2.6 on 2019-10-18 12:27

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synagogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formal_name', models.TextField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('date_of_death_after_sunset', models.BooleanField(default=False)),
                ('synagogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Synagogue')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Person')),
                ('manual_first_name', models.TextField(blank=True)),
                ('last_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_birth_after_sunset', models.BooleanField(default=False)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_of_father', to='webapp.Person')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children_of_mother', to='webapp.Person')),
            ],
            bases=('webapp.person',),
        ),
        migrations.CreateModel(
            name='MaleMember',
            fields=[
                ('yichus', django_enumfield.db.fields.EnumField(default=3, enum=webapp.models.Yichus)),
                ('cannot_get_aliya', models.BooleanField(default=False)),
                ('can_be_hazan', models.BooleanField(default=False)),
                ('can_read_torah', models.BooleanField(default=False)),
                ('can_read_haftarah', models.BooleanField(default=False)),
                ('parashat_bar_mitzvah', models.IntegerField(blank=True, null=True)),
                ('last_aliya_date', models.DateField(blank=True, null=True)),
                ('member_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Member')),
                ('wife', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='husband', to='webapp.Member')),
            ],
            bases=('webapp.member',),
        ),
    ]
