# Generated by Django 2.2.6 on 2019-10-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synagogue',
            name='admins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
