# Generated by Django 2.2.6 on 2019-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_synagogue_member_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='synagogue',
            name='in_israel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='synagogue',
            name='in_jerusalem',
            field=models.BooleanField(default=False),
        ),
    ]
