# Generated by Django 2.2.6 on 2019-11-23 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_synagogue_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malemember',
            name='last_aliya_date',
        ),
        migrations.CreateModel(
            name='ScheduledAliya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('aliya_number', models.PositiveSmallIntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_aliyot', to='webapp.MaleMember')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scheduledaliya',
            constraint=models.UniqueConstraint(fields=('date', 'aliya_number'), name='unique_scheduled_aliya'),
        ),
    ]
